version: 0.0.{build}
image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
    - dev
    - /^release\/.$/
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: ./run.ps1
clone_depth: 1
test: 'off'
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  server:
  api_key:
    secure: +WkQsLfLX+2884LCdTg6WbxK2mkPqOkEGncIDyTtG9DhIO/3HrCcAWSS98PWcLX7
  artifact: /.*\.nupkg/
  on:
    branch: master
