image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
    - dev
    - /^release\/.$/
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: ./run.ps1
clone_depth: 1
test: 'off'
deploy:
- provider: NuGet
  api_key:
    secure: 3oIYTJaSzVop/lz7vk1/gaDEYPRHC7WP1EvVMPtBHv2olsZGlT2ulFZewD6IzIGP
  username:
    secure: qC0aKO6QJRsHw5L+Q7OYew==
  on:
    branch: master
artifacts:
  - path: '**\*.nupkg'
